// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/AnalyticsService.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetTotalSales_FullMethodName        = "/analytics.AnalyticsService/GetTotalSales"
	AnalyticsService_GetAverageOrderValue_FullMethodName = "/analytics.AnalyticsService/GetAverageOrderValue"
	AnalyticsService_GetTopProducts_FullMethodName       = "/analytics.AnalyticsService/GetTopProducts"
	AnalyticsService_GetLowStockProducts_FullMethodName  = "/analytics.AnalyticsService/GetLowStockProducts"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetTotalSales(ctx context.Context, in *GetTotalSalesRequest, opts ...grpc.CallOption) (*GetTotalSalesResponse, error)
	GetAverageOrderValue(ctx context.Context, in *GetAverageOrderValueRequest, opts ...grpc.CallOption) (*GetAverageOrderValueResponse, error)
	GetTopProducts(ctx context.Context, in *GetTopProductsRequest, opts ...grpc.CallOption) (*GetTopProductsResponse, error)
	GetLowStockProducts(ctx context.Context, in *GetLowStockProductsRequest, opts ...grpc.CallOption) (*GetLowStockProductsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetTotalSales(ctx context.Context, in *GetTotalSalesRequest, opts ...grpc.CallOption) (*GetTotalSalesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalSalesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTotalSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAverageOrderValue(ctx context.Context, in *GetAverageOrderValueRequest, opts ...grpc.CallOption) (*GetAverageOrderValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAverageOrderValueResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAverageOrderValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopProducts(ctx context.Context, in *GetTopProductsRequest, opts ...grpc.CallOption) (*GetTopProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopProductsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetLowStockProducts(ctx context.Context, in *GetLowStockProductsRequest, opts ...grpc.CallOption) (*GetLowStockProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLowStockProductsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetLowStockProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetTotalSales(context.Context, *GetTotalSalesRequest) (*GetTotalSalesResponse, error)
	GetAverageOrderValue(context.Context, *GetAverageOrderValueRequest) (*GetAverageOrderValueResponse, error)
	GetTopProducts(context.Context, *GetTopProductsRequest) (*GetTopProductsResponse, error)
	GetLowStockProducts(context.Context, *GetLowStockProductsRequest) (*GetLowStockProductsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetTotalSales(context.Context, *GetTotalSalesRequest) (*GetTotalSalesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalSales not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAverageOrderValue(context.Context, *GetAverageOrderValueRequest) (*GetAverageOrderValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAverageOrderValue not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopProducts(context.Context, *GetTopProductsRequest) (*GetTopProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopProducts not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetLowStockProducts(context.Context, *GetLowStockProductsRequest) (*GetLowStockProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLowStockProducts not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetTotalSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalSalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTotalSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTotalSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTotalSales(ctx, req.(*GetTotalSalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAverageOrderValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAverageOrderValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAverageOrderValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAverageOrderValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAverageOrderValue(ctx, req.(*GetAverageOrderValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopProducts(ctx, req.(*GetTopProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetLowStockProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLowStockProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetLowStockProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetLowStockProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetLowStockProducts(ctx, req.(*GetLowStockProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotalSales",
			Handler:    _AnalyticsService_GetTotalSales_Handler,
		},
		{
			MethodName: "GetAverageOrderValue",
			Handler:    _AnalyticsService_GetAverageOrderValue_Handler,
		},
		{
			MethodName: "GetTopProducts",
			Handler:    _AnalyticsService_GetTopProducts_Handler,
		},
		{
			MethodName: "GetLowStockProducts",
			Handler:    _AnalyticsService_GetLowStockProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/AnalyticsService.proto",
}
