// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/AnalyticsService.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetTotalSales_FullMethodName        = "/analytics.AnalyticsService/GetTotalSales"
	AnalyticsService_GetAverageOrderValue_FullMethodName = "/analytics.AnalyticsService/GetAverageOrderValue"
	AnalyticsService_GetTopProducts_FullMethodName       = "/analytics.AnalyticsService/GetTopProducts"
	AnalyticsService_GetLowStockProducts_FullMethodName  = "/analytics.AnalyticsService/GetLowStockProducts"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetTotalSales(ctx context.Context, in *GetTotalSalesRequest, opts ...grpc.CallOption) (*GetTotalSalesResponse, error)
	GetAverageOrderValue(ctx context.Context, in *GetAverageOrderValueRequest, opts ...grpc.CallOption) (*GetAverageOrderValueResponse, error)
	GetTopProducts(ctx context.Context, in *GetTopProductsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProductStat], error)
	GetLowStockProducts(ctx context.Context, in *GetLowStockProductsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProductStat], error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetTotalSales(ctx context.Context, in *GetTotalSalesRequest, opts ...grpc.CallOption) (*GetTotalSalesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalSalesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTotalSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAverageOrderValue(ctx context.Context, in *GetAverageOrderValueRequest, opts ...grpc.CallOption) (*GetAverageOrderValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAverageOrderValueResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAverageOrderValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopProducts(ctx context.Context, in *GetTopProductsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProductStat], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyticsService_ServiceDesc.Streams[0], AnalyticsService_GetTopProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTopProductsRequest, ProductStat]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetTopProductsClient = grpc.ServerStreamingClient[ProductStat]

func (c *analyticsServiceClient) GetLowStockProducts(ctx context.Context, in *GetLowStockProductsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProductStat], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyticsService_ServiceDesc.Streams[1], AnalyticsService_GetLowStockProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLowStockProductsRequest, ProductStat]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetLowStockProductsClient = grpc.ServerStreamingClient[ProductStat]

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetTotalSales(context.Context, *GetTotalSalesRequest) (*GetTotalSalesResponse, error)
	GetAverageOrderValue(context.Context, *GetAverageOrderValueRequest) (*GetAverageOrderValueResponse, error)
	GetTopProducts(*GetTopProductsRequest, grpc.ServerStreamingServer[ProductStat]) error
	GetLowStockProducts(*GetLowStockProductsRequest, grpc.ServerStreamingServer[ProductStat]) error
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetTotalSales(context.Context, *GetTotalSalesRequest) (*GetTotalSalesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalSales not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAverageOrderValue(context.Context, *GetAverageOrderValueRequest) (*GetAverageOrderValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAverageOrderValue not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopProducts(*GetTopProductsRequest, grpc.ServerStreamingServer[ProductStat]) error {
	return status.Error(codes.Unimplemented, "method GetTopProducts not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetLowStockProducts(*GetLowStockProductsRequest, grpc.ServerStreamingServer[ProductStat]) error {
	return status.Error(codes.Unimplemented, "method GetLowStockProducts not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetTotalSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalSalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTotalSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTotalSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTotalSales(ctx, req.(*GetTotalSalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAverageOrderValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAverageOrderValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAverageOrderValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAverageOrderValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAverageOrderValue(ctx, req.(*GetAverageOrderValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTopProductsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).GetTopProducts(m, &grpc.GenericServerStream[GetTopProductsRequest, ProductStat]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetTopProductsServer = grpc.ServerStreamingServer[ProductStat]

func _AnalyticsService_GetLowStockProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLowStockProductsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).GetLowStockProducts(m, &grpc.GenericServerStream[GetLowStockProductsRequest, ProductStat]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetLowStockProductsServer = grpc.ServerStreamingServer[ProductStat]

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotalSales",
			Handler:    _AnalyticsService_GetTotalSales_Handler,
		},
		{
			MethodName: "GetAverageOrderValue",
			Handler:    _AnalyticsService_GetAverageOrderValue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTopProducts",
			Handler:       _AnalyticsService_GetTopProducts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLowStockProducts",
			Handler:       _AnalyticsService_GetLowStockProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/AnalyticsService.proto",
}
