// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/AnalyticsService.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalSalesRequest) Reset() {
	*x = GetTotalSalesRequest{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalSalesRequest) ProtoMessage() {}

func (x *GetTotalSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalSalesRequest.ProtoReflect.Descriptor instead.
func (*GetTotalSalesRequest) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{0}
}

func (x *GetTotalSalesRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTotalSalesRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetTotalSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders   int64                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	TotalRevenue  float64                `protobuf:"fixed64,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalSalesResponse) Reset() {
	*x = GetTotalSalesResponse{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalSalesResponse) ProtoMessage() {}

func (x *GetTotalSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalSalesResponse.ProtoReflect.Descriptor instead.
func (*GetTotalSalesResponse) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{1}
}

func (x *GetTotalSalesResponse) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *GetTotalSalesResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

type GetAverageOrderValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageOrderValueRequest) Reset() {
	*x = GetAverageOrderValueRequest{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageOrderValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageOrderValueRequest) ProtoMessage() {}

func (x *GetAverageOrderValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageOrderValueRequest.ProtoReflect.Descriptor instead.
func (*GetAverageOrderValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{2}
}

func (x *GetAverageOrderValueRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetAverageOrderValueRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetAverageOrderValueResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AverageOrderValue float64                `protobuf:"fixed64,1,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAverageOrderValueResponse) Reset() {
	*x = GetAverageOrderValueResponse{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageOrderValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageOrderValueResponse) ProtoMessage() {}

func (x *GetAverageOrderValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageOrderValueResponse.ProtoReflect.Descriptor instead.
func (*GetAverageOrderValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{3}
}

func (x *GetAverageOrderValueResponse) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

type GetTopProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopProductsRequest) Reset() {
	*x = GetTopProductsRequest{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopProductsRequest) ProtoMessage() {}

func (x *GetTopProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopProductsRequest.ProtoReflect.Descriptor instead.
func (*GetTopProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLowStockProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     int32                  `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLowStockProductsRequest) Reset() {
	*x = GetLowStockProductsRequest{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLowStockProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLowStockProductsRequest) ProtoMessage() {}

func (x *GetLowStockProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLowStockProductsRequest.ProtoReflect.Descriptor instead.
func (*GetLowStockProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{5}
}

func (x *GetLowStockProductsRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type ProductStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	UnitsSold     int64                  `protobuf:"varint,3,opt,name=units_sold,json=unitsSold,proto3" json:"units_sold,omitempty"`
	Revenue       float64                `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStat) Reset() {
	*x = ProductStat{}
	mi := &file_proto_AnalyticsService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStat) ProtoMessage() {}

func (x *ProductStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AnalyticsService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStat.ProtoReflect.Descriptor instead.
func (*ProductStat) Descriptor() ([]byte, []int) {
	return file_proto_AnalyticsService_proto_rawDescGZIP(), []int{6}
}

func (x *ProductStat) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductStat) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductStat) GetUnitsSold() int64 {
	if x != nil {
		return x.UnitsSold
	}
	return 0
}

func (x *ProductStat) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *ProductStat) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_proto_AnalyticsService_proto protoreflect.FileDescriptor

const file_proto_AnalyticsService_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/AnalyticsService.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\x14GetTotalSalesRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"_\n" +
	"\x15GetTotalSalesResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x03R\vtotalOrders\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x01R\ftotalRevenue\"\x8f\x01\n" +
	"\x1bGetAverageOrderValueRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"N\n" +
	"\x1cGetAverageOrderValueResponse\x12.\n" +
	"\x13average_order_value\x18\x01 \x01(\x01R\x11averageOrderValue\"-\n" +
	"\x15GetTopProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\":\n" +
	"\x1aGetLowStockProductsRequest\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x05R\tthreshold\"\x9e\x01\n" +
	"\vProductStat\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"units_sold\x18\x03 \x01(\x03R\tunitsSold\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock2\xf5\x02\n" +
	"\x10AnalyticsService\x12R\n" +
	"\rGetTotalSales\x12\x1f.analytics.GetTotalSalesRequest\x1a .analytics.GetTotalSalesResponse\x12g\n" +
	"\x14GetAverageOrderValue\x12&.analytics.GetAverageOrderValueRequest\x1a'.analytics.GetAverageOrderValueResponse\x12L\n" +
	"\x0eGetTopProducts\x12 .analytics.GetTopProductsRequest\x1a\x16.analytics.ProductStat0\x01\x12V\n" +
	"\x13GetLowStockProducts\x12%.analytics.GetLowStockProductsRequest\x1a\x16.analytics.ProductStat0\x01B$Z\"github.com/avnpl/go-march/api/grpcb\x06proto3"

var (
	file_proto_AnalyticsService_proto_rawDescOnce sync.Once
	file_proto_AnalyticsService_proto_rawDescData []byte
)

func file_proto_AnalyticsService_proto_rawDescGZIP() []byte {
	file_proto_AnalyticsService_proto_rawDescOnce.Do(func() {
		file_proto_AnalyticsService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_AnalyticsService_proto_rawDesc), len(file_proto_AnalyticsService_proto_rawDesc)))
	})
	return file_proto_AnalyticsService_proto_rawDescData
}

var file_proto_AnalyticsService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_AnalyticsService_proto_goTypes = []any{
	(*GetTotalSalesRequest)(nil),         // 0: analytics.GetTotalSalesRequest
	(*GetTotalSalesResponse)(nil),        // 1: analytics.GetTotalSalesResponse
	(*GetAverageOrderValueRequest)(nil),  // 2: analytics.GetAverageOrderValueRequest
	(*GetAverageOrderValueResponse)(nil), // 3: analytics.GetAverageOrderValueResponse
	(*GetTopProductsRequest)(nil),        // 4: analytics.GetTopProductsRequest
	(*GetLowStockProductsRequest)(nil),   // 5: analytics.GetLowStockProductsRequest
	(*ProductStat)(nil),                  // 6: analytics.ProductStat
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_proto_AnalyticsService_proto_depIdxs = []int32{
	7, // 0: analytics.GetTotalSalesRequest.start_date:type_name -> google.protobuf.Timestamp
	7, // 1: analytics.GetTotalSalesRequest.end_date:type_name -> google.protobuf.Timestamp
	7, // 2: analytics.GetAverageOrderValueRequest.start_date:type_name -> google.protobuf.Timestamp
	7, // 3: analytics.GetAverageOrderValueRequest.end_date:type_name -> google.protobuf.Timestamp
	0, // 4: analytics.AnalyticsService.GetTotalSales:input_type -> analytics.GetTotalSalesRequest
	2, // 5: analytics.AnalyticsService.GetAverageOrderValue:input_type -> analytics.GetAverageOrderValueRequest
	4, // 6: analytics.AnalyticsService.GetTopProducts:input_type -> analytics.GetTopProductsRequest
	5, // 7: analytics.AnalyticsService.GetLowStockProducts:input_type -> analytics.GetLowStockProductsRequest
	1, // 8: analytics.AnalyticsService.GetTotalSales:output_type -> analytics.GetTotalSalesResponse
	3, // 9: analytics.AnalyticsService.GetAverageOrderValue:output_type -> analytics.GetAverageOrderValueResponse
	6, // 10: analytics.AnalyticsService.GetTopProducts:output_type -> analytics.ProductStat
	6, // 11: analytics.AnalyticsService.GetLowStockProducts:output_type -> analytics.ProductStat
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_AnalyticsService_proto_init() }
func file_proto_AnalyticsService_proto_init() {
	if File_proto_AnalyticsService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_AnalyticsService_proto_rawDesc), len(file_proto_AnalyticsService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_AnalyticsService_proto_goTypes,
		DependencyIndexes: file_proto_AnalyticsService_proto_depIdxs,
		MessageInfos:      file_proto_AnalyticsService_proto_msgTypes,
	}.Build()
	File_proto_AnalyticsService_proto = out.File
	file_proto_AnalyticsService_proto_goTypes = nil
	file_proto_AnalyticsService_proto_depIdxs = nil
}
